//WARNING: This code was auto generated by template compiler, do not modify by hand!
//Generated on 16.05.2017 16:00:26 by NFX.Templatization.TextCSTemplateCompiler at CRAZYROGUE

using System; 
using System.Text; 
using System.Linq; 
using System.Collections.Generic; 
using NFX; 
using NFX.Wave; 
using NFX.Wave.Templatization; 

namespace Test001.Pages 
{

 ///<summary>
 /// Auto-generated from template
 ///</summary>
 public  class index : NFX.Wave.Templatization.WaveTemplate 
 {

     protected override void DoRender()
     {
       base.DoRender();
        Target.Write( index._66_S_LITERAL_0 );

     }


     #region Literal blocks content
        private const string _66_S_LITERAL_0 = @"

<!DOCTYPE html>

<html lang=""ru"" xmlns=""http://www.w3.org/1999/xhtml"">
<head>
    <meta charset=""utf-8"" />
    <title>TEST</title>
</head>
<body>
    <h1>Hello TEST!</h1>
</body>
</html>"; 
     #endregion

 }//class
}//namespace
